version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
    depends_on:
      - server

  server:
    build:
      context: ./server
    expose:
      - 8000
    depends_on:
      - database

  database:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: bowleg.historic.TORI
      MYSQL_DATABASE: exploration
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
  
  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80     # 443 HTTPS
    depends_on:
      - client
      - server

  #phpmyadmin:
  #  image: phpmyadmin:latest
  #  restart: always
  #  ports:    # Keep for now but will be removed in the future
  #    - 8080:80
  #  environment:
  #    PMA_ARBITRARY: 1

volumes:
  mysql-data: