# Stage 1: Build the React app
ARG NODE_VERSION=20.10.0

FROM node:${NODE_VERSION}-alpine as builder

WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app's source code
COPY . .

# Clear the dist directory before building
RUN rm -rf ./dist

# Build the React app
CMD npm run build